workflow fix

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -67,74 +67,73 @@ jobs:
             #- name: Database Check
             #  run: docker-compose exec -T php bin/console doctrine:schema:validate
             - name: Security Checks
-              run: docker-compose exec -T php composer req sensiolabs/security-checker
-
-      - name: Chores
-        run: docker-compose down
-      - name: Login to DockerHub Registry
-        id: dockerhub-login
-        run: |
-            if [ "${{ secrets.DOCKERHUB_PASSWORD }}" != "" ] && [ "${{ secrets.DOCKERHUB_USERNAME }}" != "" ]; then
-              echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-              echo "##[set-output name=success;]true"
-            else
-              echo "##[set-output name=success;]false"
-            fi
-      - if: steps.dockerhub-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development')
-        name: Push to docker hub
-        run: docker-compose push
-#      - name: Create kube config
-#        id: kubeconfig
-#        if: contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )
-#        run: |
-#            if [ "${{ secrets.KUBECONFIG }}" != "" ]; then
-#              printf "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
-#              echo "##[set-output name=success]true"
-#            else
-#              echo "##[set-output name=success]false"
-#            fi 
-#      - name: Set correct helm version
-#        if: (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true'
-#        run: helm init --upgrade --kubeconfig="kubeconfig.yaml"    
-#      - name: Deploy through helm
-#        id: helm-install
-#        if: (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true'
-#        run: helm upgrade $APP_NAME-$APP_ENV ./api/helm  --kubeconfig="kubeconfig.yaml" --namespace=$APP_ENV  --set settings.env=$APP_ENV,settings.debug=1
-#      - name: Install through helm
-#        if: failure() && (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true'
-#        run: helm install --name $APP_NAME-$APP_ENV ./api/helm  --kubeconfig="kubeconfig.yaml" --namespace=$APP_ENV  --set settings.env=$APP_ENV,settings.debug=1 
-#      - name: Rollout new containers
-#        if: (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true' && success()
-#        run: |
-#            kubectl rollout restart deployment/$APP_NAME-php --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
-#            kubectl rollout restart deployment/$APP_NAME-nginx --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
-#            kubectl rollout restart deployment/$APP_NAME-varnish --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
-      - name: Export release code
-        if: (success() || failure())
-        id: releasecode
-        run: |
-            export RELEASE=$APP_BUILD-$(git rev-parse --short $GITHUB_SHA)
-            echo "##[set-output name=releasename]$RELEASE"
-#      - name: Export release code
-#        if: (success() || failure())
-#        id: releasecode #version number in a more comprehensible format: 0.1.YearMonthDayHoursMinutesSeconds in UTC
-#        run: |
-#            export RELEASE=$APP_BUILD.$(date --utc +%Y%m%d%H%M%S)
-#            echo "##[set-output name=releasename]$RELEASE"
-      - name: Print release name
-        if: (success() || failure())
-        run: echo $RELEASENAME
-        env:
-            RELEASENAME: ${{ steps.releasecode.outputs.releasename }}
-      - name: Create Release
-        if: contains( github.ref, 'master' ) && steps.kubeconfig.outputs.success == 'true' && ( success() || failure() )
-        id: create_release
-        uses: actions/create-release@v1
-        continue-on-error: true
-        env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
-        with:
-            tag_name: ${{ steps.releasecode.outputs.releasename }}
-            release_name: ${{ steps.releasecode.outputs.releasename }}
-            draft: false
-            prerelease: false
+              run: docker-compose exec -T php composer req sensiolabs/security-checkers
+            - name: Chores
+              run: docker-compose down
+            - name: Login to DockerHub Registry
+              id: dockerhub-login
+              run: |
+                  if [ "${{ secrets.DOCKERHUB_PASSWORD }}" != "" ] && [ "${{ secrets.DOCKERHUB_USERNAME }}" != "" ]; then
+                    echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+                    echo "##[set-output name=success;]true"
+                  else
+                    echo "##[set-output name=success;]false"
+                  fi
+            - if: steps.dockerhub-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development')
+              name: Push to docker hub
+              run: docker-compose push
+            #      - name: Create kube config
+            #        id: kubeconfig
+            #        if: contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )
+            #        run: |
+            #            if [ "${{ secrets.KUBECONFIG }}" != "" ]; then
+            #              printf "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
+            #              echo "##[set-output name=success]true"
+            #            else
+            #              echo "##[set-output name=success]false"
+            #            fi 
+            #      - name: Set correct helm version
+            #        if: (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true'
+            #        run: helm init --upgrade --kubeconfig="kubeconfig.yaml"    
+            #      - name: Deploy through helm
+            #        id: helm-install
+            #        if: (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true'
+            #        run: helm upgrade $APP_NAME-$APP_ENV ./api/helm  --kubeconfig="kubeconfig.yaml" --namespace=$APP_ENV  --set settings.env=$APP_ENV,settings.debug=1
+            #      - name: Install through helm
+            #        if: failure() && (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true'
+            #        run: helm install --name $APP_NAME-$APP_ENV ./api/helm  --kubeconfig="kubeconfig.yaml" --namespace=$APP_ENV  --set settings.env=$APP_ENV,settings.debug=1 
+            #      - name: Rollout new containers
+            #        if: (contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true' && success()
+            #        run: |
+            #            kubectl rollout restart deployment/$APP_NAME-php --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
+            #            kubectl rollout restart deployment/$APP_NAME-nginx --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
+            #            kubectl rollout restart deployment/$APP_NAME-varnish --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
+            - name: Export release code
+              if: (success() || failure())
+              id: releasecode
+              run: |
+                  export RELEASE=$APP_BUILD-$(git rev-parse --short $GITHUB_SHA)
+                  echo "##[set-output name=releasename]$RELEASE"
+            #      - name: Export release code
+            #        if: (success() || failure())
+            #        id: releasecode #version number in a more comprehensible format: 0.1.YearMonthDayHoursMinutesSeconds in UTC
+            #        run: |
+            #            export RELEASE=$APP_BUILD.$(date --utc +%Y%m%d%H%M%S)
+            #            echo "##[set-output name=releasename]$RELEASE"
+            - name: Print release name
+              if: (success() || failure())
+              run: echo $RELEASENAME
+              env:
+                  RELEASENAME: ${{ steps.releasecode.outputs.releasename }}
+            - name: Create Release
+              if: contains( github.ref, 'master' ) && steps.kubeconfig.outputs.success == 'true' && ( success() || failure() )
+              id: create_release
+              uses: actions/create-release@v1
+              continue-on-error: true
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
+              with:
+                  tag_name: ${{ steps.releasecode.outputs.releasename }}
+                  release_name: ${{ steps.releasecode.outputs.releasename }}
+                  draft: false
+                  prerelease: false
